bundler_args: --without extras
before_script:
  # From: https://github.com/jonleighton/poltergeist/blob/v1.0.0/.travis.yml#L5-7
  - git submodule init
  - git submodule update
  - bundle exec rake core:verify
branches:
  only:
    - master
cache:
  bundler: true
services:
  - redis-server
script: bundle exec rake
rvm:
  - 2.2.2
